name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_thousandeyes_token: ${{ secrets.TE_API_TOKEN }}
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform-debug.log
        run: terraform apply -auto-approve -var="change_reason=Automated apply from main branch"

      - name: Upload Terraform Debug Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-debug-log
          path: terraform-debug.log
